# Generated by Django 2.0.1 on 2018-01-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knuapp', '0002_account_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='lasted',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='account',
            name='td_get',
            field=models.BooleanField(default=False),
        ),
    ]
