# Generated by Django 2.0.1 on 2018-01-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knuapp', '0003_auto_20180131_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='lasted',
            field=models.TimeField(auto_now=True),
        ),
    ]
