# Generated by Django 2.0.1 on 2018-01-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knuapp', '0006_auto_20180131_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='lasted',
            field=models.CharField(default='18-01-31', max_length=128),
        ),
    ]
